spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # defines a 15 second grace period for requests after shutdown
  config:
    import: "optional:configserver:"    # import configs from config server WHEN available
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # timeout on waiting to connect to config server
      request-read-timeout: 5000    # timeout on writing to read configs from config server
      fail-fast: false              # connection failures are fatal; set to 'true' in prod
      retry:                        # only enabled if 'fail-fast: true'
        max-attempts: 6
        initial-interval: 1000      # ms
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 # max time to wait (in ms) getting a connection from the pool
      maximum-pool-size: 5     # max # of connections for hikari to keep alive

server:
  port: 9001
  # pg 80-81
  tomcat:
    # Duration between TCP connection established and actually receiving the request (help prevent DoS attacks).
    # A thread is reserved when the TCP connection is established, and the default timeout is 20 seconds (yikes)
    connection-timeout: 2s
    keep-alive-timeout: 15s # how long to keep the connection open whil waiting for new HTTP requests
    threads:
      # lower the max and spare when running locally to reserve resources
      max: 50
      min-spare: 5 # always running, created at startup
  shutdown: graceful # enable graceful shutdown

polar:
  greeting: Welcome to the local book catalog!

management:
  endpoints:
    web:
      exposure:
        include: refresh